linker/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import RegisterUser, ChannelUser

app_name = 'usuario'

urlpatterns = [

    path('entrar/', auth_views.LoginView.as_view(
        template_name='login.html',
        redirect_authenticated_user=True
    ), name='login'),
    path('sair/', auth_views.LogoutView.as_view(), name='logout'),
    path('cadastrar/', RegisterUser.as_view(), name='register'),
    path('channels', ChannelUser.as_view(), name='channel_user'),


]

linker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('linker.aggregator.urls', namespace='home')),
    path('usuarios/', include('linker.accounts.urls', namespace="accounts")),
    path('', include('linker.website.urls', namespace="website")),
    
]

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL , document_root=settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

linker/website/urls.py
from django.urls import path
from .views import Website

app_name = 'usuario'

urlpatterns = [
    path('', Website.as_view(), name='homepage'),
]

linker/website/models.py
from django.db import models

# Create your models here.

linker/website/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.http import JsonResponse

class Website(TemplateView):
    template_name = "website.html"

linker/website/templates/website.html
{% extends 'base_website.html' %}

{% load static %}
{% load widget_tweaks %}

{% block content %}

    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand" href="{% url 'website:homepage' %}">Linker</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars ms-1"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
                    <li class="nav-item"><a class="nav-link" href="#services">Serviços</a></li>
                    <li class="nav-item"><a class="nav-link" href="#about">Sobre</a></li>
                    <li class="nav-item"><a class="nav-link" href="#team">Time</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Masthead-->
    <header class="masthead">
        <div class="container">
            <div class="masthead-subheading">Bem vindo</div>
            <div class="masthead-heading text-uppercase">Armazene seus links em um só lugar!</div>
            <a class="btn btn-primary btn-xl text-uppercase" href="{% url 'accounts:login' %}">Começar a usar</a>
        </div>
    </header>

    <!-- Services-->
    <section class="page-section" id="services">
        <div class="container">
            <div class="text-center">
                <h2 class="section-heading text-uppercase">Serviços</h2>
                <h3 class="section-subheading text-muted">Com o linker você pode:</h3>
            </div>
            <div class="row text-center">
                <div class="col-md-4">
                    <span class="fa-stack fa-4x">
                        <i class="fas fa-circle fa-stack-2x text-primary"></i>
                        <i class="fas fa-archive fa-stack-1x fa-inverse"></i>
                    </span>
                    <h4 class="my-3">Armazenar</h4>
                    <p class="text-muted">Armazene links de conteúdos de estudo, tutoriais, artigos, videos do YouTube e muitos mais.</p>
                </div>
                <div class="col-md-4">
                    <span class="fa-stack fa-4x">
                        <i class="fas fa-circle fa-stack-2x text-primary"></i>
                        <i class="fas fa-share-alt fa-stack-1x fa-inverse"></i>
                    </span>
                    <h4 class="my-3">Compartilhar</h4>
                    <p class="text-muted">Compartilhe seus links salvos no linker com qualquer amigo(a) dentro da plataforma, é rápido e prático.</p>
                </div>
                <div class="col-md-4">
                    <span class="fa-stack fa-4x">
                        <i class="fas fa-circle fa-stack-2x text-primary"></i>
                        <i class="fas fa-lock fa-stack-1x fa-inverse"></i>
                    </span>
                    <h4 class="my-3">Organizar</h4>
                    <p class="text-muted">Organize seus links de maneira fácil atribuindo categorias a eles. Separe links por workspaces</p>
                </div>
            </div>
        </div>
    </section>


    <!-- About-->
    <section class="page-section" id="about">
        <div class="container">
            <div class="text-center">
                <h2 class="section-heading text-uppercase">Sobre</h2>
                <h3 class="section-subheading text-muted">
                    A ideia do projeto nasceu com a demanda de uma aplicação que possa auxiliar estudantes ou qualquer pessoa que 
                    tenha dificuldades em organizar materiais online. O Linker tem o objetivo de possibilitar que as diferentes informações 
                    no meio online possam ser armazenadas, organizadas e compartilhadas. O projeto foi idealizado e construido pelos estudantes do curso de 
                    Sistemas de Informação do campus de Picos-PI onde a princípio era para ser somente uma plataforma de uso interno.
                </h3>
            </div>
   
        </div>
    </section>

    <!-- Team-->
    <section class="page-section bg-light" id="team">
        <div class="container">
            <div class="text-center">
                <h2 class="section-heading text-uppercase">NOSSA EQUIPE INCRÍVEL</h2>
                <h3 class="section-subheading text-muted">Composta por três jovens membros</h3>
            </div>
            <div class="row">
                <div class="col-lg-4">
                    <div class="team-member">
                        <img class="mx-auto rounded-circle" src="{% static 'agency/assets/img/team/1.jpg' %}" alt="..." />
                        <h4>Thaliane Gomes</h4>
                        <p class="text-muted">Quality Assurance</p>
                        <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="team-member">
                        <img class="mx-auto rounded-circle"  src="{% static 'agency/assets/img/team/3.jpg' %}" alt="..." />
                        <h4>Marcos Paulo</h4>
                        <p class="text-muted">Lead Developer</p>
                        <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="team-member">
                        <img class="mx-auto rounded-circle"  src="{% static 'agency/assets/img/team/2.jpg' %}" alt="..." />
                        <h4>Samuel Oliveira</h4>
                        <p class="text-muted">WEB Developer</p>
                        <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-8 mx-auto text-center"><p class="large text-muted">Estudantes do curso de Sistemas de Informação pela Universidade Federal do Piauí - Campus Picos</p></div>
            </div>
        </div>
    </section>

{% endblock %}