linker/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import RegisterUser, ChannelUser

app_name = 'usuario'

urlpatterns = [

    path('entrar/', auth_views.LoginView.as_view(
        template_name='login.html',
        redirect_authenticated_user=True
    ), name='login'),
    path('sair/', auth_views.LogoutView.as_view(), name='logout'),
    path('cadastrar/', RegisterUser.as_view(), name='register'),
    path('channels', ChannelUser.as_view(), name='channel_user'),


]

linker/aggregator/urls.py
from django.urls import path
from .views import *

app_name = 'links'

urlpatterns = [
    path('', IndexPage.as_view(), name='index'),
    path('links/', LinksAggregator.as_view(), name='links'),
    path('links/delete/', LinkDelete.as_view(), name='links_delete'),
    path('links/buscar/', LinksSearch.as_view(), name='links_search'),
    path('amigos/', Friends.as_view(), name='friends'),
    path('amigos/remover/', FriendshipRemove.as_view(), name='friendship_remove'),
    path('usuarios/autocomplete/', UsersAutoComplete.as_view(), name='users_autocomplete'),
    path('usuarios/amizade/', FriendshipRequest.as_view(), name='friendship_request'),
    path('workspaces/', Spaces.as_view(), name='workspaces'),
    path('workspaces/remover/', WorkspaceRemove.as_view(), name='workspace_remove'),
    path('workspaces/novo/', WorkspaceCreate.as_view(), name='workspace_add'),
    path('tags/', TagsCreate.as_view(), name='tags_add'),
    path('compartilhar/', ShareLink.as_view(), name='share_link'),
    path('notificacoes/', NotificationsList.as_view(), name='notifications_list'),
]

linker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('linker.aggregator.urls', namespace='home')),
    path('usuarios/', include('linker.accounts.urls', namespace="accounts")),
    path('', include('linker.website.urls', namespace="website")),
    
]

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL , document_root=settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

linker/aggregator/models.py
from django.db import models
from linker.core.models import AuditModel
from linker.accounts.models import User

from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType

class Workspaces(AuditModel):
    name = models.CharField("Nome do espaço de trabalho", max_length=50)
    members = models.ManyToManyField(User, verbose_name="Membros", related_name="members")
    created_by = models.ForeignKey(User, verbose_name="Criado por", on_delete=models.PROTECT) 

    def __str__(self):
        return self.name


class Tags(AuditModel):
    name = models.CharField("Nome da tag", max_length=50)
    created_by = models.ForeignKey(User, verbose_name="Criado por", 
        on_delete=models.PROTECT, related_name="user") 

    def __str__(self):
        return self.name


class Links(AuditModel):
    title = models.CharField("Título", max_length=50)
    url = models.TextField("URL")
    description = models.TextField("Descrição")
    tags = models.ManyToManyField(Tags, verbose_name="Tags", related_name="tags")
    workspaces = models.ManyToManyField(Workspaces, verbose_name="Espaços de trabalho", 
        related_name="workspaces")
    created_by = models.ForeignKey(User, verbose_name="Criado por", on_delete=models.PROTECT) 
    is_active = models.BooleanField(default=True)

    @property
    def tags_list(self):
        tags = self.tags.all()
        list_tags = []
        [list_tags.append(tag.name) for tag in tags]

        return ", ".join(list_tags)
    def __str__(self):
        return self.title


class Friendships(AuditModel):
    user = models.ForeignKey(User, verbose_name="Usuário", 
        related_name="User", on_delete=models.PROTECT) 
    friend = models.ForeignKey(User, verbose_name="Amigo", 
        on_delete=models.PROTECT) 
    is_active = models.BooleanField(default=False)
    was_rejected = models.BooleanField(default=False)
    was_accepted = models.BooleanField(default=False)
    is_pending = models.BooleanField(default=False)

    def __str__(self):
        return "{}".format(self.friend.full_name)


class LinkShared(AuditModel):
    user = models.ForeignKey(User, verbose_name="Usuário", 
        related_name="link_user", on_delete=models.PROTECT) 
    friends = models.ManyToManyField(User, verbose_name="Amigo") 
    link = models.ForeignKey(Links, verbose_name="Link", 
        on_delete=models.PROTECT) 
    is_active = models.BooleanField(default=True)
    
    def __str__(self):
        return "{}".format(self.link.title)


class Notification(AuditModel):
    TYPES_NOTIFICATION_CHOICES = (
        ("link", "Link"),
        ("friendships", "Friendships"),
        ("workspace", "Workspace"),
    )

    create_by = models.ForeignKey(User, verbose_name="Usuário", 
        related_name="notification_user", on_delete=models.PROTECT) 
    send_to = models.ForeignKey(User, verbose_name="Usuário", 
        related_name="notification_send", on_delete=models.PROTECT) 
    has_read = models.BooleanField(default=False)
    tipo_servico = models.CharField(
        choices=TYPES_NOTIFICATION_CHOICES,
        max_length=50
    )
    friendship = models.ForeignKey(Friendships, verbose_name="amizades", 
        related_name="friendship", on_delete=models.PROTECT) 

linker/aggregator/views.py
from django.views.generic import TemplateView, View
from django.shortcuts import render
from django.http import JsonResponse
import json
from django.db.models import Q

from linker.aggregator.models import (
    Tags,
    Links,
    Workspaces,
    Friendships,
    LinkShared,
    Notification,
)
from linker.accounts.models import User
from .helpers import format_users_list_result
import pusher

pusher_client = pusher.Pusher(
    app_id="1194177",
    key="7f66f8f13624f8813eac",
    secret="709d8715aba90973802f",
    cluster="us2",
    #   ssl=True
    ssl=False,
)


class IndexPage(TemplateView):
    template_name = "aggregator/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["tags_user"] = Tags.objects.filter(created_by=self.request.user)

        context["links"] = Links.objects.filter(created_by=self.request.user)

        context["spaces"] = Workspaces.objects.filter(
            Q(created_by=self.request.user) | Q(members=self.request.user)
        ).distinct()

        context["friends"] = Friendships.objects.filter(user=self.request.user)

        return context


class TagCreate(View):
    def post(self, request, *args, **kwargs):
        datas = json.loads(request.body.decode("utf-8"))
        new_tag = datas["name"]

        tag = Tags.objects.create(name=new_tag, created_by=self.request.user)
        return JsonResponse({"message": "ok", "tag_id": tag.id}, safe=False)


class LinksAggregator(View):
    def post(self, request, *args, **kwargs):
        datas = json.loads(request.body.decode("utf-8"))
        print(datas)

        if datas["workspace"] == "false" or datas["workspace"] == False :
            print('NO SPACE')
            tags = Tags.objects.filter(id__in=datas["tags"])
            new_link = Links.objects.create(
                title=datas["title"],
                url=datas["url"],
                description=datas["description"],
                created_by=self.request.user,
            )

            new_link.tags.add(*tags)
        else:
            workspace = Workspaces.objects.get( id=int(datas["workspace"]) )
            new_link = Links.objects.create(
                title=datas["title"],
                url=datas["url"],
                description=datas["description"],
                created_by=self.request.user,
            )
            new_link.workspaces.add(workspace)
            
            for member in workspace.members.all():
                pusher_client.trigger(str(member.uuid_channel), "reload-spaces-links", {
                    "space":workspace.id
                })
            pusher_client.trigger(str(workspace.created_by.uuid_channel), "reload-spaces-links", {
                "space":workspace.id
            })

        return JsonResponse({"message": "Link criado com sucesso!"}, safe=False)

    def get(self, request):
        links_response = []
        shareds_me = LinkShared.objects.filter(
            friends__id__in=[self.request.user.id],
            is_active=True
        ).values_list("link", flat=True)

        ids = list(shareds_me)

        links = Links.objects.filter(
            Q(Q(created_by=self.request.user) & Q(is_active=True) & Q(workspaces=None)) | Q(id__in=ids)
        )

        for link in links:

            created_by = ""
            tags = link.tags_list
            shared = False
            if link.created_by.id != self.request.user.id:
                created_by = "Compartilhado por: " + link.created_by.full_name
                tags = ""
                shared = True

            links_response.append(
                {
                    "title": link.title,
                    "description": link.description,
                    "url": link.url,
                    "tags": tags,
                    "id": link.id,
                    "created_by": created_by,
                    "shared": shared,
                }
            )

        return JsonResponse(
            status=200,
            data={"links": links_response},
        )


class LinkDelete(View):
    def post(self, request, *args, **kwargs):
        datas = json.loads(request.body.decode("utf-8"))

        if datas["is_shared"] == "true":
            print("Compartilhado")
            link_id = int(datas["link"])

            link_shared = LinkShared.objects.get(
                link__id=link_id,
                friends__id__in=[self.request.user.id]
            )
            link_shared.is_active = False
            link_shared.save()
        else:
            print("MEU")
            link = Links.objects.get(
                id=int(datas["link"])
            )
            link.is_active =False
            link.save()
        
        if link.workspaces.first():
            for member in link.workspaces.first().members.all():  
                pusher_client.trigger(str(member.uuid_channel), "reload-spaces-links", {
                    "space":link.workspaces.first().id
                })
                
            pusher_client.trigger(str(link.workspaces.first().created_by.uuid_channel), "reload-spaces-links", {
                "space":link.workspaces.first().id
            })

        return JsonResponse({"message": "Link criado com sucesso!"}, safe=False)


class LinksSearch(View):
    def post(self, request, *args, **kwargs):
        datas = json.loads(request.body.decode("utf-8"))
        links_response = []
        print(datas["tags"])

        shareds_me = LinkShared.objects.filter(
                Q(
                    Q(friends__id__in=[self.request.user.id])&
                    Q(is_active=True)
                )&
                Q(
                    Q(link__title__icontains=datas["string"])|
                    Q(link__description__icontains=datas["string"])|
                    Q(user__username__icontains=datas["string"])|
                    Q(user__full_name__icontains=datas["string"])
                )
            ).values_list("link", flat=True)

        ids = list(shareds_me)
        if len(datas["tags"]) > 0:
            links = Links.objects.filter(
                Q(
                    Q(
                        Q(created_by=self.request.user) & Q(is_active=True) & Q(workspaces=None)
                    ) | Q(id__in=ids)
                )&
                Q(
                    Q(title__icontains=datas["string"])|
                    Q(description__icontains=datas["string"])|
                    Q(id__in=ids)
                )
                &
                Q(
                    tags__id__in=datas["tags"]
                )
            ).distinct()
        else:
            links = Links.objects.filter(
                Q(
                    Q(
                        Q(created_by=self.request.user) & Q(is_active=True) & Q(workspaces=None)
                    ) | Q(id__in=ids)
                )&
                Q(
                    Q(title__icontains=datas["string"])|
                    Q(description__icontains=datas["string"])|
                    Q(id__in=ids)
                )
            ).distinct()


        for link in links:

            created_by = ""
            tags = link.tags_list
            shared = False
            if link.created_by.id != self.request.user.id:
                created_by = "Compartilhado por: " + link.created_by.full_name
                tags = ""
                shared = True

            links_response.append(
                {
                    "title": link.title,
                    "description": link.description,
                    "url": link.url,
                    "tags": tags,
                    "id": link.id,
                    "created_by": created_by,
                    "shared": shared,
                }
            )


        print(datas)
        return JsonResponse({"links": links_response}, safe=False)



class Friends(View):
    def get(self, request):
        friends_list = {}
        friendships = Friendships.objects.filter(user=self.request.user, is_active=True)

        for friendship in friendships:
            friends_list[friendship.id] = {
                "friendship_id": friendship.id,
                "friend_name": friendship.friend.full_name,
                "friend_username": friendship.friend.username,
            }

        return JsonResponse(
            status=200,
            data={"friendships": friends_list},
        )

    def post(self, request, *args, **kwargs):
        return JsonResponse(
            status=200,
            data={"friends-post": "marcos"},
        )


class FriendshipRemove(View):
    def post(self, request, *args, **kwargs):
        datas = json.loads(request.body.decode("utf-8"))

        try:
            friendships = Friendships.objects.get(
                id=datas["id"], user=self.request.user, is_active=True
            )
            friendships.is_active = False
            friendships.save()

            friendships_reverse = Friendships.objects.get(
                user=friendships.friend, friend=self.request.user, is_active=True
            )
            friendships_reverse.is_active = False
            friendships_reverse.save()

            pusher_client.trigger(
                str(friendships.friend.uuid_channel), "reload-friend-list", {}
            )

            return JsonResponse(
                status=200,
                data={"detail": "vinculo de amizade removido"},
            )

        except Exception as e:
            print(e)

            return JsonResponse(
                status=400,
                data={"friends-post": "marcos"},
            )


class Spaces(View):
    def get(self, request):
        workspaces_list = {}
        friendships = Friendships.objects.filter(user=self.request.user)

        workspaces = Workspaces.objects.filter(
            Q(created_by=self.request.user) | Q(members=self.request.user)
        ).distinct()

        for space in workspaces:

linker/aggregator/templates/aggregator/components/header.html
{% load static %}

<style>

</style>

<header id="header">
	<h1 id="title-header">
		Linker
	</h1>
</header>

linker/aggregator/templates/aggregator/components/main.html
<div id="content">

    <div id="form-search">
        <form>
            <i class="fas fa-search"></i>
            <input type="text" id="input_search" placeholder="Buscar por link" onkeyup="searchLink(this)">
        </form>
    </div>
    
    <div id="tags-list">
        <a title="Adicionar nova tag" onclick="addTagModal()">
            <i class="fas fa-plus-circle"></i>
        </a>
        
        <div id="tags-content">
        </div>
    </div>
    
    
    <div id="links-list-content">


    </div>
    
    <button class="button-add-link btn" onclick="addLinkModal()">
        <i class="fas fa-plus"></i>
    </button>


</div>

<div id="content-spaces" style="display:none">

    <div style="display: flex; flex-direction: row; align-items: center">
        
        <h4 id="current-space" style="color: white; margin-left: 3%; margin-right: 3%% ;  margin-top:2%">
        </h4>

        <div id="tags-content-space" style="margin-top: 2%; margin-left: 3%">
        </div>

    </div>

    
    
    <div id="links-list-content-space">


    </div>
    
    <button class="button-add-link btn" id="btnAddSpaceModal" onclick="addLinkSpaceModal(this)">
        <i class="fas fa-plus"></i>
    </button>


</div>

linker/aggregator/templates/aggregator/components/menu-list.html
{% load static %}

<div class="menu-list" id="friends">
	
	<div class="header-list">
		<h3 id="title-header-list">
			<i class="fas fa-users"></i> Amigos
		</h3>
	</div>

	<div id="friends_content" lass="col-md-12">
	</div>

	<button class="button-add-friend btn" onclick="addFriendModal()">
		<i class="fas fa-plus"></i>
	</button>

</div>

<div class="menu-list hidden" id="workspaces">
	
	<div class="header-list">
		<h3 id="title-header-list">
			<i class="fab fa-weebly"></i>orkspaces
		</h3>
	</div>

	<div id="workspaces_content" lass="col-md-12">
	</div>

	<button class="button-add-friend btn" onclick="addWorkspaceModal()">
		<i class="fas fa-plus"></i>
	</button>

</div>

linker/aggregator/templates/aggregator/components/moda-share-link.html
{% load static %}
<!-- Modal -->
<div class="modal fade" id="shareLink" tabindex="-1" role="dialog" 
    aria-labelledby="addFriend" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content modal-remove-friend">

      <div class="modal-header" style="border: none">
        <h5 class="modal-title">
            Compartilhar com amigos
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    
      <div class="modal-body" id="modal-body-friendship">
        <form class="col-md-12 info" id="form-request-friendship">
            
            <div class="box">
                <div class="box-input">
                    <div class="text-center" style="padding: 10px;">
                        <i class="fas fa-user"></i>
                    </div>

                    <input id="friend-selected" autocomplete="off" type="text" onkeyup="searchUser(this, true)">
                </div>
            </div>
            
            <div id="autocomplete-list-friend"></div>
            <div id="list-friends">
            

            </div>

        </form>
      </div>
    
      <div class="modal-footer info" id="modal-footer-friendship" style="border: none">
        <button type="button" class="btn" data-dismiss="modal">Cancelar</button>
        <button type="button" id="btn-share" onClick="shareLinkForFriends(this)"
          class="btn btn-add-friend">
          Compartilhar
        </button>
      </div>
    
    </div>
  </div>
</div>

linker/aggregator/templates/aggregator/components/modal-add-friend.html
{% load static %}
<!-- Modal -->
<div class="modal fade" id="addFriend" tabindex="-1" role="dialog" 
    aria-labelledby="addFriend" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content modal-remove-friend">

      <div class="modal-header" style="border: none">
        <h5 class="modal-title">
            Adicionar usuário na lista de amigos
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    
      <div class="modal-body" id="modal-body-friendship">
        <form class="col-md-12 info" id="form-request-friendship">
            
            <div class="box">
                <div class="box-input">
                    <div class="text-center" style="padding: 10px;">
                        <i class="fas fa-user"></i>
                    </div>

                    <input id="user-selected" autocomplete="off" type="text" onkeyup="searchUser(this, false)">
                </div>
            </div>
            
            <div id="autocomplete-list">
                
            </div>

        </form>
      </div>
    
      <div class="modal-footer info" id="modal-footer-friendship" style="border: none">
        <button type="button" class="btn" data-dismiss="modal">Cancelar</button>
        <button type="button" onClick="addNewFriend()"
          class="btn btn-add-friend">
          Adicionar
        </button>
      </div>
    
    </div>
  </div>
</div>

linker/aggregator/templates/aggregator/components/modal-add-link-space.html
{% load static %}
<!-- Modal -->
<div class="modal fade bd-example-modal-lg" id="modalAddLinkSpace" tabindex="-1" role="dialog" 
    aria-labelledby="addFriend" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content modal-remove-friend">

      <div class="modal-header" style="border: none">
        <h5 class="modal-title">
            Adicionar novo link em - <span id="currentSpaceNameModal"></span>
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    
      <div class="modal-body" id="modal-body-friendship">
        <form class="col-md-12 info" id="form-request-friendship">
            
            <div class="box">

                <div style="display: flex;">
                    <div style="display: flex; flex-direction:column; width: 49%; margin-right: 2%">
                        <label>Título</label>
                        <div class="box-input">
                            <div class="text-center"  style="padding: 10px;">
                                <i class="fas fa-signature"></i>
                            </div>
                            <input id="link-title-space" autocomplete="off" type="text">
                        </div>
                    </div>

                    
                    <div style="display: flex; flex-direction:column; width: 49%;">
                        <label>URL/Link</label>
                        <div class="box-input">
                            <div class="text-center"  style="padding: 10px;">
                                <i class="fas fa-link"></i>
                            </div>
                            <input id="link-url-space" autocomplete="off" type="text">
                        </div>
                    </div>
                </div>

                <div style="display: flex; flex-direction:column; width: 100%;">
                    <label>Descrição</label>
                    <div class="box-input">
                        <div class="text-center" style="padding: 10px;">
                            <i class="fas fa-align-left"></i>
                        </div>
                        <input id="link-description-space" autocomplete="off" type="text" style="width: 100%">
                    </div>

                </div>

            </div>
            
        </form>
      </div>
    
      <div class="modal-footer info" style="border: none">
        <button type="button" class="btn" data-dismiss="modal">Cancelar</button>
        <button type="button" onClick="addNewLinkSpace()"
          class="btn btn-add-friend">
          Adicionar
        </button>
      </div>
    
    </div>
  </div>
</div>

linker/aggregator/templates/aggregator/components/modal-add-link.html
{% load static %}
<!-- Modal -->
<div class="modal fade bd-example-modal-lg" id="addLink" tabindex="-1" role="dialog" 
    aria-labelledby="addFriend" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content modal-remove-friend">

      <div class="modal-header" style="border: none">
        <h5 class="modal-title">
            Adicionar novo link
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    
      <div class="modal-body" id="modal-body-friendship">
        <form class="col-md-12 info" id="form-request-friendship">
            
            <div class="box">

                <div style="display: flex;">
                    <div style="display: flex; flex-direction:column; width: 49%; margin-right: 2%">
                        <label>Título</label>
                        <div class="box-input">
                            <div class="text-center"  style="padding: 10px;">
                                <i class="fas fa-signature"></i>
                            </div>
                            <input id="link-title" autocomplete="off" type="text">
                        </div>
                    </div>

                    
                    <div style="display: flex; flex-direction:column; width: 49%;">
                        <label>URL/Link</label>
                        <div class="box-input">
                            <div class="text-center"  style="padding: 10px;">
                                <i class="fas fa-link"></i>
                            </div>
                            <input id="link-url" autocomplete="off" type="text">
                        </div>
                    </div>
                </div>

                <div style="display: flex; flex-direction:column; width: 100%;">
                    <label>Descrição</label>
                    <div class="box-input">
                        <div class="text-center" style="padding: 10px;">
                            <i class="fas fa-align-left"></i>
                        </div>
                        <input id="link-description" autocomplete="off" type="text" style="width: 100%">
                    </div>

                </div>

                <label>Tags</label>
                <div id="tags-new-link">

                </div>
            </div>
            
        </form>
      </div>
    
      <div class="modal-footer info" style="border: none">
        <button type="button" class="btn" data-dismiss="modal">Cancelar</button>
        <button type="button" onClick="addNewLink()"
          class="btn btn-add-friend">
          Adicionar
        </button>
      </div>
    
    </div>
  </div>
</div>

linker/aggregator/templates/aggregator/components/modal-add-tag.html
{% load static %}
<!-- Modal -->
<div class="modal fade" id="addTag" tabindex="-1" role="dialog" 
    aria-labelledby="addFriend" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content modal-remove-friend">

      <div class="modal-header" style="border: none">
        <h5 class="modal-title">
            Adicionar nova tag
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    
      <div class="modal-body" id="modal-body-friendship">
        <form class="col-md-12 info" id="form-request-friendship">
            
            <div class="box">
                <div class="box-input">
                    <div class="text-center" style="padding: 10px;">
                        <i class="fas fa-cube"></i>
                    </div>

                    <input id="new-tag" autocomplete="off" type="text">
                </div>
            </div>
            
        </form>
      </div>
    
      <div class="modal-footer info" style="border: none">
        <button type="button" class="btn" data-dismiss="modal">Cancelar</button>
        <button type="button" onClick="addNewTag()"
          class="btn btn-add-friend">
          Adicionar
        </button>
      </div>
    
    </div>
  </div>
</div>

linker/aggregator/templates/aggregator/components/modal-add-workspace.html
{% load static %}
<!-- Modal -->
<div class="modal fade" id="addWorkspace" tabindex="-1" role="dialog" 
    aria-labelledby="addFriend" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content modal-remove-friend">

      <div class="modal-header" style="border: none">
        <h5 class="modal-title">
            Adicionar novo workspace
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>


      <div class="modal-body" id="modal-body-friendship">
        <form class="col-md-12 info" id="form-request-friendship">
            
            <div class="box">
                <label>Nome do WorkSpace:</label>
                <div class="box-input">
                    <div class="text-center" style="padding: 10px;">
                        <i class="fas fa-cube"></i>
                    </div>

                    <input id="new-workspace" autocomplete="off" type="text" autofocus>
                </div>
            </div>

            <div class="box">
              <label>Membros:</label>
                <div class="box-input">
                    <div class="text-center" style="padding: 10px;">
                        <i class="fas fa-user"></i>
                    </div>

                    <input id="friend-selected-space" autocomplete="off" type="text" onkeyup="searchUser(this, true)">
                </div>
            </div>
            
            <div id="autocomplete-list-space"></div>
            <div id="list-friends-space">
            

            </div>

        </form>
      </div>

      {% comment %} <div class="modal-body" id="modal-body-friendship">
        <form class="col-md-12 info" id="form-request-friendship">
            
            <div class="box">
                <div class="box-input">
                    <div class="text-center" style="padding: 10px;">
                        <i class="fas fa-cube"></i>
                    </div>

                    <input id="new-workspace" autocomplete="off" type="text">
                </div>
            </div>
            
        </form>
      </div> {% endcomment %}
    
      <div class="modal-footer info" id="modal-footer-friendship" style="border: none">
        <button type="button" class="btn" data-dismiss="modal">Cancelar</button>
        <button type="button" onClick="addNewWorkspace()"
          class="btn btn-add-friend">
          Adicionar
        </button>
      </div>
    
    </div>
  </div>
</div>

linker/aggregator/templates/aggregator/components/options-list.html
{% load static %}

<div id="nav-options-select">
	
	<div 
		class="card-option-select selected" 
		onClick="selectItem(this)"
		data-option="friends"
	>
		<i class="fas fa-users"></i>
	</div>
	
	<div 
		class="card-option-select" 
		onClick="selectItem(this)"
		data-option="workspaces"
	>
		<i class="fab fa-weebly"></i>
	</div>

	<div class="boxBtnsBottom">

		<div style="margin-bottom: 1.5em">
			<a class="btnBottom btnNotification" onClick="showNotificationModal()">
				<div id="count-notifications">
					0
				</div>
				<i class="far fa-bell"></i>
			</a>
		</div>
	
		<a class="btnConfig" href="{% url 'accounts:logout' %}" title="Sair do sistema">
			<i class="fas fa-sign-out-alt"></i>
		</a>

	</div>

</div>  