linker/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import RegisterUser, ChannelUser

app_name = 'usuario'

urlpatterns = [

    path('entrar/', auth_views.LoginView.as_view(
        template_name='login.html',
        redirect_authenticated_user=True
    ), name='login'),
    path('sair/', auth_views.LogoutView.as_view(), name='logout'),
    path('cadastrar/', RegisterUser.as_view(), name='register'),
    path('channels', ChannelUser.as_view(), name='channel_user'),


]

linker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('linker.aggregator.urls', namespace='home')),
    path('usuarios/', include('linker.accounts.urls', namespace="accounts")),
    path('', include('linker.website.urls', namespace="website")),
    
]

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL , document_root=settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

linker/website/urls.py
from django.urls import path
from .views import Website

app_name = 'usuario'

urlpatterns = [
    path('', Website.as_view(), name='homepage'),
]

linker/accounts/models.py
import re
import uuid
from django.db import models
from django.urls import reverse
from django.core import validators
from django.contrib.auth.models import AbstractBaseUser, UserManager, PermissionsMixin
from linker.core.models import AuditModel

class User(AbstractBaseUser, PermissionsMixin, AuditModel):

    username = models.CharField(
        'Usuário', max_length=200, unique=True, validators=[
        validators.RegexValidator(
            re.compile('^[\w.@+-]+$'),
            'Informe um nome de usuário válido. '
            'Este valor deve conter apenas letras, números '
            'e os caracteres: @/./+/-/_ .'
            , 'invalid'
        )
        ], help_text='Um nome curto que será usado para identificá-lo de forma única na plataforma'
    )
    full_name = models.CharField('Nome Completo', max_length=100)
    email = models.EmailField('Email', max_length=100, unique=True)
    is_staff = models.BooleanField('is staff', default=False)
    uuid_channel = models.UUIDField("UUID ", default=uuid.uuid4, editable=False)
    
    def __str__(self):
        return self.full_name
    
    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def get_absolute_url(self):
        return reverse('accounts:login')

    def get_short_name(self):
        return self.full_name.split(' ')[0]

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

class Friends(AuditModel):
    user = models.ForeignKey(User, related_name="user_request_friend",verbose_name="Usuário", on_delete=models.CASCADE)
    friend = models.ForeignKey(User, related_name="user_friend",verbose_name="Usuário", on_delete=models.CASCADE)
    is_active = models.BooleanField("Amizade ativa")

linker/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, PasswordResetForm
from django import forms
from .models import *
from django.contrib.auth import get_user_model


class UserForm(UserCreationForm):

	class Meta:
		model = User
		fields = ['full_name', 'username', 'email']

	def clean_email(self):
		email = self.cleaned_data.get('email')

		# Valido o email para ser obrigatório
		if email == '':
			raise forms.ValidationError('O endereço de email é obrigatório.')
		return email

		if email and User.objects.filter(email=email).count():
			raise forms.ValidationError(
				'Este endereço de email já está em uso. Por favor, use um email diferente.')
		return email

linker/accounts/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, View
from django.http import JsonResponse
from .forms import UserForm
from .models import User


class RegisterUser(CreateView):
    template_name = "register.html"
    form_class = UserForm
    
class ChannelUser(View):
    
    def get(self, request):
        return JsonResponse(
            status=200,
            data={"channel" : request.user.uuid_channel },
        )

linker/accounts/templates/login.html
{% extends 'base_website.html' %}

{% load static %}
{% load widget_tweaks %}

{% block content %}

    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand" href="{% url 'website:homepage' %}">Linker</a>
        </div>
    </nav>
    <!-- Masthead-->
    <header class="masthead">
        <div class="form form-login col-sm-12" class="col-md-5 mx-auto">
            
          <h1 class="title-form">Boas-Vindas de volta!</h1>
          <p class="subtitle-form">Estamos felizes em te ver novamente!</p>
          
          {% if form.errors %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger" style="width:92%">
                <strong>{{ error|escape }}</strong>
              </div>
            {% endfor %}
          {% endif %}

          
          <form method="post" class="" autocomplete="off">{% csrf_token %}

            <div class="box-input">
              <label>Nome de usuário</label>
              <input autocomplete="false" required autofocus type="text" name="username">
            </div>

            <div class="box-input">
              <label>Sua senha secreta</label>
              <input type="password" required name="password">
            </div>

            <a class="forget-pass" href="#">Esqueceu sua senha?</a>

            <button type="submit" class="btn-form">
              Entrar
            </button>

            <label > Novo aqui ? 
              <a class="forget-pass" href="{% url 'accounts:register' %}"> Cadastre-se</a>
            </label>
            <br>
            <br>
            <br>
          </form>
            
        </div>
    </header>

{% endblock %}

linker/accounts/templates/register.html
{% extends 'base_website.html' %}

{% load static %}
{% load widget_tweaks %}

{% block content %}

    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand" href="{% url 'website:homepage' %}">Linker</a>
        </div>
    </nav>
    <!-- Masthead-->
    <header class="masthead">
        <div class="form-register form" class="col-md-5 mx-auto">
            
          <h1 class="title-form">Olá, seja bem-vindo(a)!</h1>
          <p class="subtitle-form">Crie uma nova conta e comece a usar!</p>

          {% if form.errors %}
              <div class="alert alert-danger" style="width:92%">
                <ol style="text-align:left">
                  {% for field in form %}
                      {% for error in field.errors %}
                              <li>
                                <strong>{{ error|escape }}</strong>
                              </li>
                      {% endfor %}
                  {% endfor %}
                </ol>
              
              </div>

              {% for error in form.non_field_errors %}
                  <div class="alert alert-danger">
                      <strong>{{ error|escape }}</strong>
                  </div>
              {% endfor %}
          {% endif %}

          <form method="post" class="" autocomplete="off"> {% csrf_token %}

            <div class="box-input">
              <label>Nome *</label>
              <input autocomplete="false" required autofocus type="text" name="full_name">
            </div>

            <div class="box-input">
              <label>Nome de usuário *</label>
              <input autocomplete="false"  type="text" name="username">
            </div>
            <div class="box-input">
              <label>E-mail *</label>
              <input autocomplete="false" type="email" name="email">
            </div>

            <div style="display:flex; width:100%;">
              <div class="box-input-2" style="margin-right: 4%;">
                <label>Senha *</label>
                <input required type="password" name="password1">
              </div>

              <div class="box-input-2">
                <label>Repetir Senha *</label>
                <input required type="password" name="password2">
              </div>
          </div>

            <button type="submit" class="btn-form">
              Cadastrar
            </button>
       
            <label > Já possui conta ? 
              <a class="forget-pass" href="{% url 'accounts:login' %}"> Entrar</a>
            </label>
          </form>
            
        </div>
    </header>

{% endblock %}